name: RFAA
channels:
  - predector
  - pyg
  - bioconda
  - pytorch
  - nvidia
  - biocore
  - conda-forge
dependencies:
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - dgl=1.1.2
  - deepdiff=6.7.1
  - icecream=2.1.3
  - networkx=3.2.1
  - harfbuzz=6.0.0
  - hhsuite=3.3.0
  - numpy=1.26.4
  - openbabel=3.1.1
  - opt_einsum=3.3.0
  - pandas=2.2.1
  - psipred=4.01
  - python=3.10.13
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - scipy=1.12.0
  - setuptools=69.1.1
  - signalp6=6.0g
  - tqdm=4.66.2
  - psutil=5.9.8
  - joblib=1.3.2
  - pip:
      - assertpy==1.1
      - git+https://github.com/NVIDIA/dllogger.git@0540a43971f4a8a16693a9de9de73c1072020769
      - e3nn==0.3.3
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - pynvml==11.0.0
      - wandb==0.12.0
