name: RFAA
channels:
  - predector
  - pyg
  - bioconda
  - pytorch
  - nvidia
  - biocore
  - conda-forge
dependencies:
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.2.0
  - blas=2.121
  - blas-devel=3.9.0
  - blast-legacy=2.2.26
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cryptography=42.0.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cycler=0.12.1
  - dbus=1.13.6
  - deepdiff=6.7.1
  - dgl=1.1.2
  - executing=2.0.1
  - expat=2.6.1
  - fftw=3.3.10
  - filelock=3.13.1
  - flatbuffers=22.12.06
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - gast=0.4.0
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.13
  - grpcio=1.51.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.38
  - gzip=1.13
  - h5py=3.9.0
  - harfbuzz=6.0.0
  - hdf5=1.14.1
  - hhsuite=3.3.0
  - icecream=2.1.3
  - icu=70.1
  - idna=3.6
  - importlib-metadata=7.0.2
  - jinja2=3.1.3
  - joblib=1.3.2
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.0.20
  - libcups=2.3.3
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.1
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libgrpc=1.51.1
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libuv=1.48.0
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - markdown=3.5.2
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - metis=5.1.1
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nccl=2.20.5.1
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.98
  - numpy=1.26.4
  - openbabel=3.1.1
  - openjpeg=2.5.0
  - opt_einsum=3.3.0
  - ordered-set=4.1.0
  - orjson=3.9.15
  - packaging=23.2
  - pandas=2.2.1
  - pcre2=10.43
  - perl=5.32.1
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.43.2
  - ply=3.11
  - protobuf=4.21.12
  - psipred=4.01
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyg=2.5.0
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-flatbuffers=24.3.6
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - re2=2023.02.01
  - readline=8.2
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.1.1
  - signalp6=6.0g
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.4.0
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.4
  - tqdm=4.66.2
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - unzip=6.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yarl=1.9.4
  - zip=3.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.9.3
      - assertpy==1.1
      - configparser==6.0.1
      - git+https://github.com/NVIDIA/dllogger.git@0540a43971f4a8a16693a9de9de73c1072020769
      - docker-pycreds==0.4.0
      - e3nn==0.3.3
      - gitdb==4.0.11
      - gitpython==3.1.42
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - opt-einsum-fx==0.1.4
      - pathtools==0.1.2
      - promise==2.3
      - pynvml==11.0.0
      - pyrsistent==0.20.0
      - pyyaml==6.0.1
      - sentry-sdk==1.41.0
      - shortuuid==1.0.12
      - smmap==5.0.1
      - subprocess32==3.5.4
      - wandb==0.12.0
